# Generated by Django 3.1.3 on 2020-11-27 15:59

import administracion.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('perId', models.AutoField(db_column='per_id', primary_key=True, serialize=False, unique=True)),
                ('perDni', models.CharField(db_column='per_dni', max_length=8)),
                ('perNombres', models.CharField(db_column='per_nombres', max_length=50)),
                ('perApellidos', models.CharField(db_column='per_apellidos', max_length=50)),
                ('perFecnac', models.DateField(db_column='per_fecnac')),
                ('perSexo', models.CharField(db_column='per_sexo', max_length=1)),
                ('perCorreo', models.CharField(db_column='per_correo', max_length=20)),
                ('perCelular', models.CharField(db_column='per_celular', max_length=15)),
                ('perObservacion', models.CharField(db_column='per_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_persona',
            },
        ),
        migrations.CreateModel(
            name='LaboralModel',
            fields=[
                ('labId', models.AutoField(db_column='lab_id', primary_key=True, serialize=False, unique=True)),
                ('labEmpresa', models.CharField(db_column='lab_empresa', max_length=50)),
                ('labCargo', models.CharField(db_column='lab_cargo', max_length=50)),
                ('labFecini', models.DateField(db_column='lab_fecini')),
                ('labFecfin', models.DateField(db_column='lab_fecfin')),
                ('labContacnombre', models.CharField(db_column='lab_contacnombre', max_length=50)),
                ('labContaccelular', models.CharField(db_column='lab_contaccelular', max_length=15)),
                ('labObservacion', models.CharField(db_column='lab_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('perId', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, related_name='laboralesPersona', to='administracion.personamodel')),
            ],
            options={
                'db_table': 't_laboral',
            },
        ),
        migrations.CreateModel(
            name='HobbieModel',
            fields=[
                ('hobId', models.AutoField(db_column='hob_id', primary_key=True, serialize=False, unique=True)),
                ('hobDescripcion', models.CharField(db_column='hob_descripcion', max_length=50)),
                ('hobObservacion', models.CharField(db_column='hob_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('perId', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, related_name='hobbiesPersona', to='administracion.personamodel')),
            ],
            options={
                'db_table': 't_hobbie',
            },
        ),
        migrations.CreateModel(
            name='HabilidadModel',
            fields=[
                ('habId', models.AutoField(db_column='hab_id', primary_key=True, serialize=False, unique=True)),
                ('habDescripcion', models.CharField(db_column='hab_descripcion', max_length=50)),
                ('habObservacion', models.CharField(db_column='hab_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('perId', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, related_name='habilidadesPersona', to='administracion.personamodel')),
            ],
            options={
                'db_table': 't_habilidad',
            },
        ),
        migrations.CreateModel(
            name='ConocimientoModel',
            fields=[
                ('conociId', models.AutoField(db_column='conoci_id', primary_key=True, serialize=False, unique=True)),
                ('conociDescripcion', models.CharField(db_column='conoci_descripcion', max_length=50)),
                ('conociFecini', models.DateField(db_column='conoci_fecini')),
                ('conociFecfin', models.DateField(db_column='conoci_fecfin')),
                ('conociCestudios', models.CharField(db_column='conoci_cestudios', max_length=50)),
                ('conociHoras', models.CharField(db_column='conoci_horas', max_length=50)),
                ('conociObservacion', models.CharField(db_column='conoci_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('perId', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, related_name='conocimientosPersona', to='administracion.personamodel')),
            ],
            options={
                'db_table': 't_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='AcademicoModel',
            fields=[
                ('acadId', models.AutoField(db_column='acad_id', primary_key=True, serialize=False, unique=True)),
                ('acadNivel', models.CharField(db_column='acad_nivel', max_length=50)),
                ('acadCestudios', models.CharField(db_column='acad_cestudios', max_length=50)),
                ('acadCarrera', models.CharField(db_column='acad_carrera', max_length=50)),
                ('acadObservacion', models.CharField(db_column='acad_observacion', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('perId', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, related_name='academicosPersona', to='administracion.personamodel')),
            ],
            options={
                'db_table': 't_academico',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuId', models.AutoField(db_column='usu_id', primary_key=True, serialize=False)),
                ('usuCorreo', models.EmailField(db_column='usu_correo', max_length=254, unique=True, verbose_name='Correo')),
                ('usuNombre', models.CharField(db_column='usu_nombre', max_length=50)),
                ('usuFono', models.CharField(db_column='usu_fono', max_length=15)),
                ('usuCumple', models.DateField(blank=True, db_column='usu_cumple', null=True)),
                ('password', models.TextField(db_column='usu_pass', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 't_usuario',
            },
            managers=[
                ('objects', administracion.models.ManejoUsuario()),
            ],
        ),
    ]
